#!/bin/bash

python -m pip install -r requirements.txt --user
if command -v Rscript &> /dev/null
then
    Rscript 'install.packages("shinylight", repos = "https://cloud.r-project.org")'
fi
python main.py